### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Playzapyt** [HirziDevs/CCBG#2]
So when i add the mod to minecraft it dose not work nothing happens it just works like a normal cobblestone gen pls help

**Comment by HirziDevs** [comment]
What version minecraft do you use? And do you enable Beta APIs?

**Comment by Playzapyt** [comment]
> What version minecraft do you use? And do you enable Beta APIs?

Im in school so i use Education edtion so There is no beta APIs and the version is 1.21.03 i i have to use 1.2.4

**Comment by HirziDevs** [comment]
I'm sorry, CCBG doesn't support Minecraft Education Edition, becouse CCBG require Beta API to work.

**Comment by Playzapyt** [comment]
> I'm sorry, CCBG doesn't support Minecraft Education Edition, becouse CCBG require Beta API to work.

Ok

**Comment by Playzapyt** [comment]
Do you know any other one that dose the same?

**Comment by HirziDevs** [comment]
There is another addon that generate random ore generator too, but i think its not updated to latest version of minecraft bedrock. Thats why i create CCBG

**Comment by Playzapyt** [comment]
> There is another addon that generate random ore generator too, but i think its not updated to latest version of minecraft bedrock. Thats why i create CCBG

Do you know what its called?
